---
version: 3.8.5
name: ⚡️ 闪电网络
description: ⚡️ 闪迪网络
url: https://lightningcn.com
repository: https://github.com/jekyll/jekyll
timezone: America/Los_Angeles
twitter:
  username: danielsocials
logo: "/img/logo-2x.png"
google_analytics_id: UA-135565163-1
google_site_verification: 

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: "/img/twitter-card.png"

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

feed:
  categories:
    - release

sass:
  style: compressed

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- icomoon-selection.json
- readme.md
